<a href="https://colab.research.google.com/github/Alkasingh04/DeepLearningProjects/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00: Pytorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/oo_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor

### Creating Tensors

#### Scalar

Pytorch tensor are created using 'torch.Tensors': https://pytorch.org/docs/stable/tensors.html

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:

scalar.ndim

0

In [5]:
## Get tensor back as python int
scalar.item()

7

In [6]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:

# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR = torch.tensor([[[1,2],[11,13]],
                        [[12,14],[6,9]],
                        [[2,4],[5,17]]])
TENSOR

tensor([[[ 1,  2],
         [11, 13]],

        [[12, 14],
         [ 6,  9]],

        [[ 2,  4],
         [ 5, 17]]])

In [19]:
TENSOR.ndim

3

In [20]:

TENSOR.shape


torch.Size([3, 2, 2])

### Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural networks leran is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

Torch Random Tensor = https://pytorch.org/docs/stable/generated/torch.rand.html

In [21]:
### Create a random Tensor

random_tensor = torch.rand(3,4)
random_tensor, random_tensor.dtype

(tensor([[0.5950, 0.2049, 0.5771, 0.2054],
         [0.2136, 0.1840, 0.7040, 0.3922],
         [0.9864, 0.4947, 0.3087, 0.8424]]),
 torch.float32)

In [22]:
random_tensor.ndim

2

In [23]:
## Create a random tensor of size (3, 4)
random_tensor = torch.rand(4,4,4)
random_tensor

tensor([[[0.1632, 0.6017, 0.0502, 0.6392],
         [0.8219, 0.7032, 0.1163, 0.9927],
         [0.1189, 0.7829, 0.0038, 0.9930],
         [0.5898, 0.6353, 0.8603, 0.7164]],

        [[0.0806, 0.3941, 0.3487, 0.8852],
         [0.1885, 0.5004, 0.9446, 0.6765],
         [0.3478, 0.6677, 0.5051, 0.7840],
         [0.9391, 0.7208, 0.1933, 0.5088]],

        [[0.7601, 0.6504, 0.9670, 0.6733],
         [0.8054, 0.8432, 0.0020, 0.5176],
         [0.2047, 0.9286, 0.0234, 0.5761],
         [0.7799, 0.8179, 0.2030, 0.9258]],

        [[0.0559, 0.4023, 0.1158, 0.4370],
         [0.4304, 0.8535, 0.8333, 0.5323],
         [0.0745, 0.4738, 0.4302, 0.1771],
         [0.3531, 0.3249, 0.0260, 0.7868]]])

In [24]:
random_tensor.ndim

3

In [25]:
### Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
torch.rand(size = (3,5))

tensor([[0.7475, 0.9449, 0.7760, 0.6314, 0.2974],
        [0.7439, 0.3742, 0.1162, 0.4783, 0.7171],
        [0.1206, 0.7976, 0.3395, 0.3661, 0.9514]])

## Zeros and Ones

In [27]:
Zeros = torch.zeros(size = (4,4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
Zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
# Create a tensor of all Ones
Ones = torch.ones(size = (4,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
Ones*random_tensor

tensor([[[0.1632, 0.6017, 0.0502, 0.6392],
         [0.8219, 0.7032, 0.1163, 0.9927],
         [0.1189, 0.7829, 0.0038, 0.9930],
         [0.5898, 0.6353, 0.8603, 0.7164]],

        [[0.0806, 0.3941, 0.3487, 0.8852],
         [0.1885, 0.5004, 0.9446, 0.6765],
         [0.3478, 0.6677, 0.5051, 0.7840],
         [0.9391, 0.7208, 0.1933, 0.5088]],

        [[0.7601, 0.6504, 0.9670, 0.6733],
         [0.8054, 0.8432, 0.0020, 0.5176],
         [0.2047, 0.9286, 0.0234, 0.5761],
         [0.7799, 0.8179, 0.2030, 0.9258]],

        [[0.0559, 0.4023, 0.1158, 0.4370],
         [0.4304, 0.8535, 0.8333, 0.5323],
         [0.0745, 0.4738, 0.4302, 0.1771],
         [0.3531, 0.3249, 0.0260, 0.7868]]])

In [31]:
Ones.dtype

torch.float32

In [32]:
random_tensor.dtype

torch.float32



### Creating a range of Tensors and tensors-like



In [33]:

# Use torch.range and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 1, end = 1000, step = 77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [34]:
torch.__version__

'2.6.0+cu124'

### Creating Tensors Like

In [35]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

### Notes: Tensor Datatype is one of the big 3 major issues with PyTorch we will run into.
1. Tensors not right data type.
2. Tensors not right shape.
3. Tensor not on the right device.

Precion in computing:https://en.wikipedia.org/wiki/Precision_(computer_science)

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False) # what datatype is the tensor (e.g. float32 or float16)
                               ## https://pytorch.org/docs/stable/tensors.html
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [40]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [41]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [43]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.Long)
int_32_tensor

AttributeError: module 'torch' has no attribute 'Long'

In [44]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [45]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use 'tensor.device'

In [47]:
# Create a Tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9800, 0.5535, 0.9259, 0.6643],
        [0.5864, 0.0770, 0.7339, 0.0846],
        [0.2801, 0.3612, 0.5980, 0.8071]])

In [48]:
### Find sonme details about some_tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9800, 0.5535, 0.9259, 0.6643],
        [0.5864, 0.0770, 0.7339, 0.0846],
        [0.2801, 0.3612, 0.5980, 0.8071]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations:
1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [58]:
### Create a Tensor
tensor = torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [59]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [61]:
tensor - 10

tensor([ 0, 10, 20])

In [62]:
# Tryout Pytorch Inbuilt functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [63]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication

In [67]:
## Element wise Multiplication
tensor = torch.tensor([4,5,6])

# tensor * tensor
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equals: tensor([16, 25, 36])


In [68]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(77)

In [69]:
tensor

tensor([4, 5, 6])

In [71]:
# Matrix Multiplication by hand
value4*4 + 5*5 +6*6


77

In [73]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(77)
CPU times: user 1.64 ms, sys: 973 µs, total: 2.61 ms
Wall time: 2.53 ms


In [75]:
%%time
torch.matmul(tensor , tensor)

CPU times: user 457 µs, sys: 0 ns, total: 457 µs
Wall time: 336 µs


tensor(77)